# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13fcec7b5bb25ca5f69b2c2fb7b87f34fcb8bcdfe1ed15f2b44b41836269cb74c285253e26df1bf0bf7cd1527323d449e1abc71ca4e85e0686d8d444eee16b76

test:
  secret_key_base: 7eee977937eda37d557287e5a73f141eedb84b1ba97210930989d1f6c03aeca0059328ec123420cc78d886f58249bd49a2848324c1432c22bb11058eafa4a145

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
